# Generated by Django 2.0.3 on 2018-04-03 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserCoinBox_Comment', models.CharField(max_length=150)),
                ('UserCoinBox_Comment_Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoinBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_UserCoinBox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsUserCoinBox', to='UserCoinBox.UserCoinBox'),
        ),
        migrations.AddField(
            model_name='comment',
            name='UserCoinBox_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssUserCoinBox', to=settings.AUTH_USER_MODEL),
        ),
    ]
