# Generated by Django 2.0.3 on 2018-04-03 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_projects_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='profile_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('Production_House', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('profile_projects_Message', models.CharField(max_length=280)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('profile_projects_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='profile_projects_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile_Projects.profile_projects'),
        ),
    ]
