# Generated by Django 2.0.2 on 2018-04-03 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quick_Requirements_Comment', models.CharField(max_length=150)),
                ('Comment_Quick_Requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentQuick_Requirements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quick_Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quick_Requirements_Crew_Size', models.IntegerField()),
                ('Quick_Requirements_New_Requirement', models.BooleanField()),
                ('Quick_Requirements_Requirement_Description', models.CharField(max_length=200)),
                ('Quick_Requirements_Shoot_Category', models.CharField(max_length=200)),
                ('Quick_Requirements_Shooting_Region', models.CharField(max_length=200)),
                ('Quick_Requirements_Tentative_Dates', models.DateField(auto_now_add=True)),
                ('Quick_Requirements_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Quick_Requirements_Modified_Date', models.DateTimeField(auto_now_add=True)),
                ('Quick_Requirements_Creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quick_Requirements_Creator', to=settings.AUTH_USER_MODEL)),
                ('Quick_Requirements_From_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Requirements', to=settings.AUTH_USER_MODEL)),
                ('Quick_Requirements_Recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recipent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Quick_Requirements_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuthorQuick_Requirements', to='Quick_Requirements.Quick_Requirements'),
        ),
    ]
