# Generated by Django 2.0.2 on 2018-04-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quick_requirements',
            name='Quick_Requirements_Tentative_Dates',
            field=models.DateField(),
        ),
    ]
