# Generated by Django 2.0.2 on 2018-03-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='modified_date',
        ),
    ]
