# Generated by Django 2.0.2 on 2018-04-03 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Review', '0002_auto_20180326_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Rating',
            new_name='Review_Rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Review_Text',
            new_name='Review_Review_Text',
        ),
        migrations.AddField(
            model_name='review',
            name='Review_Create_Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='Review_Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='Review_Modified_Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
