# Generated by Django 2.0.2 on 2018-04-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0003_auto_20180403_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Review_Review_Text',
            new_name='Review_Text',
        ),
    ]
