# Generated by Django 2.0.3 on 2018-04-03 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_works_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlatformWorks_Client_Name', models.CharField(max_length=200)),
                ('PlatformWorks_Project_Name', models.CharField(max_length=200)),
                ('PlatformWorks_Project_Details', models.CharField(max_length=200)),
                ('PlatformWorks_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('PlatformWorks_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_works', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='platform_works_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_works.PlatformWorks'),
        ),
    ]
