# Generated by Django 2.0.2 on 2018-04-03 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_City', models.CharField(max_length=100)),
                ('Search_Key_Word', models.CharField(max_length=200)),
                ('Search_Range', models.IntegerField(max_length=200)),
                ('Search_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Search_Modified_Date', models.DateTimeField(auto_now_add=True)),
                ('Search_Creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Search', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentSearch', to='Search.Search'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Search_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SearchcommentSearch', to=settings.AUTH_USER_MODEL),
        ),
    ]
