# Generated by Django 2.0.3 on 2018-04-03 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Musician_Daily_Charges', models.CharField(max_length=200)),
                ('Musician_Description', models.CharField(max_length=500)),
                ('Musician_Financial_Available', models.BooleanField(default=False)),
                ('Musician_Genre', models.CharField(max_length=200)),
                ('Musician_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Musician_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='musician_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.Musician'),
        ),
    ]
